FROM node:alpine AS builder

COPY package.json svelte.config.js postcss.config.cjs tailwind.config.cjs /app/
COPY src /app/src

WORKDIR /app
RUN npm install
RUN npm run build


FROM node:alpine

COPY --from=builder /app/build /app/
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/

EXPOSE 3000

CMD node app/index.js

