/* tslint:disable:ordered-imports max-line-length */
// ----------------------
// <auto-generated>
//    Generated using CodeGenerator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from SIL.XForge.Scripture.Models.SFProject
// </auto-generated>
// ----------------------

import { DomainModelConfig } from '@xforge-common/models/domain-model';
import { SFProjectRef, SFProjectUserRef, SFUserRef, SyncJobRef } from './sfdomain-model.generated';
import { SFProject } from './sfproject';
import { SFProjectUser } from './sfproject-user';
import { SFUser } from './sfuser';
import { SyncJob } from './sync-job';
import { TextData } from './text-data';

// All resource, resource ref, and realtime doc types should be added to schema and generated into this config
export const SFDOMAIN_MODEL_CONFIG: DomainModelConfig = {
  resources: [SFProject, SFProjectUser, SFUser, SyncJob],
  resourceRefs: [SFProjectRef, SFProjectUserRef, SFUserRef, SyncJobRef],
  realtimeDocs: [TextData]
};
