// ----------------------
// <auto-generated>
//    Generated using CodeGenerator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from SIL.XForge.Scripture.Models.SFProjectResource
// </auto-generated>
// ----------------------


import { DomainModelConfig } from '@xforge-common/models/domain-model';
import { SyncJob, SyncJobRef, SFProjectData, SFProjectDataRef, SFUser, SFUserRef, SFProjectUser, SFProjectUserRef, SFProject, SFProjectRef } from './sfproject.generated';
import { TextData } from './text-data';

// All resource, resource ref, and realtime doc types should be added to schema and generated into this config
export const SFDOMAIN_MODEL_CONFIG: DomainModelConfig = {
 resources: [ SyncJob,
		SFProjectData,
		SFUser,
		SFProjectUser,
		SFProject ],
 resourceRefs: [ SyncJobRef,
		SFProjectDataRef,
		SFUserRef,
		SFProjectUserRef,
		SFProjectRef ],
 realtimeDocs: [ TextData ]};
