# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "NathanielPaulus/xenial64-xforge"

  config.vm.hostname = "vag-u1604-xf"

  config.vm.provider "virtualbox" do |vb|
    vb.name="vag-u1604-xf"
    vb.gui = true
    vb.cpus = 4
    # At least 3 GiB of RAM is needed to run tests.
    vb.memory = "4096"
  end

  config.vm.provision "shell", privileged: false, inline: <<~SHELL
    set -eux -o pipefail

    # Delete and generate unique host keys until handled by base box.
    sudo rm -v /etc/ssh/ssh_host_*
    sudo dpkg-reconfigure openssh-server

    git config --global user.email "#{`git config --get user.email`.strip}"
    git config --global user.name "#{`git config --get user.name`.strip}"

    cd ~/src/web-languageforge
    git pull --ff-only --recurse-submodules
    ./refreshDeps.sh

    sudo npm install -g @angular/cli@6.1.5

    # Until baked into base box:

    # Let VS Code watch lots of files.
    sudo tee -a /etc/sysctl.conf >/dev/null <<< 'fs.inotify.max_user_watches=524288'
    sudo sysctl -p # Only needed if we want to use the change before rebooting.

    sudo mkdir -p /var/lib/scriptureforge/sync
    sudo chown $USER:$USER -R /var/lib/scriptureforge

    sudo apt-get install -y paratext-8.0
    cp -aL /usr/share/applications/paratext8.desktop ~/Desktop/development-tools/
    chmod +x ~/Desktop/development-tools/paratext8.desktop
  SHELL
end
