# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "NathanielPaulus/xenial64-xforge"

  config.vm.hostname = "vag-u1604-xf"

  config.vm.provider "virtualbox" do |vb|
    vb.name="vag-u1604-xf"
    vb.gui = true
    vb.cpus = 4
    # At least 3 GiB of RAM is needed to run tests.
    vb.memory = "4096"
  end

  config.vm.provision "shell", privileged: false, inline: <<~SHELL
    set -eux -o pipefail

    # Delete and generate unique host keys until handled by base box.
    sudo rm -v /etc/ssh/ssh_host_*
    sudo dpkg-reconfigure openssh-server

    git config --global user.email "#{`git config --get user.email`.strip}"
    git config --global user.name "#{`git config --get user.name`.strip}"

    cd ~/src/web-languageforge
    git pull --ff-only --recurse-submodules
    ./refreshDeps.sh

    sudo npm install -g @angular/cli@6.1.5
  SHELL
end
