angular.module('palaso.ui.m3ulink', [])
	.config(['$compileProvider', function($compileProvider) {
		// Angular uses a whitelist to determine what URLs are allowed in
		// <a href="{{somevalue}}"> elements. By default, data: URLs are not
		// allowed. We don't want to just allow any data: URL as that could
		// introduce a security hole, so we will base64-encode a URL fragment
		// like "http://server.name/" and use that specific fragment as the
		// *only* kind of data: URLs to allow.
		var href = document.location.href;
		var startAt = href.indexOf('://');
		var firstSlash = href.indexOf('/', startAt + 3);
		var firstUrlPart = href.substring(0, firstSlash); // protocol://server.name
		var allowedUrl = firstUrlPart;
		var encoded = window.btoa(allowedUrl);
		if (encoded[encoded.length-1] == '=') {
			// Last three bytes of B64-encoded string might not match if any
			// padding characters exist, so trim back to the first full block
			// that is guaranteed to match.
			encoded = encoded.substring(0, encoded.length-3);
		}

		var oldWhitelist = $compileProvider.aHrefSanitizationWhitelist();
		// Only add this if we haven't added it already
		if (oldWhitelist.source.indexOf(encoded) == -1) {
			var newWhitelist = RegExp(oldWhitelist.source + '|^\\s*data:audio/x-mpegurl;charset=utf-8;base64,' + encoded);
			$compileProvider.aHrefSanitizationWhitelist(newWhitelist);
		}
	}])
	// Autogenerated M3U link. Call like <a m3ulink filename="foo.mp3">...</a>
	.directive('m3ulink', function() {
		return {
			restrict : 'A',
			replace : false,
			scope : {
				filename: "@",
			},
			controller: ["$scope", "$attrs", function($scope, $attrs) {
				$scope.makeBase64Url = function(filename) {
					// Use trick from http://stackoverflow.com/q/470832 to
					// retrieve an absolute URL (including server & protocol).
					// This doesn't work in IE 6, but who cares? It works in
					// IE 7+ and all other browsers.
					var a = document.createElement('a');
					a.href = filename;
					var absoluteUrl = a.href;
					a.remove();

					var basename;
					var lastSlash = filename.lastIndexOf('/');
					if (lastSlash == -1) {
						basename = filename;
					} else {
						basename = filename.substring(lastSlash+1, filename.length);
					}
					var lastDot = basename.lastIndexOf('.');
					if (lastDot != -1) {
						basename = basename.substring(0, lastDot);
					}
					$attrs.$set('download', basename + '.m3u');

					// Construct data: URL to produce the correct .m3u
					var b64Url = window.btoa(absoluteUrl);
					$attrs.$set('href', "data:audio/x-mpegurl;charset=utf-8;base64," + b64Url);
				}
			}],
			link : function(scope, element, attrs, controller) {
				scope.$watch('filename', function(newval) {
					if (newval) {
						scope.makeBase64Url(newval);
					}
				});
			}
		};
  })
  ;
