// This file is generated by a gulp task from website-instances.ejs and WebsiteInstances.json. Do not directly modify!

export const websiteInstances = {

  // scriptureforge.localhost sites
  'scriptureforge.localhost': 'local',
  'jamaicanpsalms.scriptureforge.localhost': 'local',
  'demo.scriptureforge.localhost': 'local',

  // qa.scriptureforge.org
  'qa.scriptureforge.org': 'qa',

  // scriptureforge.org
  'scriptureforge.org': 'live',

  // jamaicanpsalms.com
  'jamaicanpsalms.scriptureforge.org': 'live',

  // waaqwiinaagiwritings.org
  'waaqwiinaagiwritings.org': 'live',

  // languageforge.localhost sites
  'languageforge.localhost': 'local',

  // qa.languageforge.org
  'qa.languageforge.org': 'qa',

  // languageforge.org
  'languageforge.org': 'live',

};
