// This file is generated by a gulp task from website-instances.ejs and WebsiteInstances.json. Do not directly modify!

export const websiteInstances = {

  // scriptureforge.org
  'scriptureforge.org': 'live',

  // local development
  'localhost': 'local',

  // qa.languageforge.org
  'qa.languageforge.org': 'qa',

  // languageforge.org
  'languageforge.org': 'live',

};
