# template, copy into env folder and change the values, then add as a patch to the kustomization.yaml file

- op: replace
  path: /spec/rules/0/host
  value: languageforge.org
- op: replace
  path: /spec/tls/0/hosts
  value:
    - languageforge.org
# Revert base's pathType change until prod migrates from ingress-nginx to Traefik.
# This apparently isn't necessary, but I'm being conservative.
# Remove this op when prod migrates.
- op: replace
  path: /spec/rules/0/http/paths/0/pathType
  value: ImplementationSpecific
